// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBiYw_-AWeeFVOifODL0SGxXf27H2bY8',
    appId: '1:163795736504:web:315a82fe2eb25fafe0614d',
    messagingSenderId: '163795736504',
    projectId: 'testing-bf7e5',
    authDomain: 'testing-bf7e5.firebaseapp.com',
    storageBucket: 'testing-bf7e5.appspot.com',
    measurementId: 'G-HGSV9Q6X38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vp-LMyIaU_AXpys-Lb_d8KBn3uuScbs',
    appId: '1:163795736504:android:f822cafe82d5560ee0614d',
    messagingSenderId: '163795736504',
    projectId: 'testing-bf7e5',
    storageBucket: 'testing-bf7e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCk9GfxK8xXIrRWG-zjsuODBI4xrAdX1E',
    appId: '1:163795736504:ios:137df7707817c591e0614d',
    messagingSenderId: '163795736504',
    projectId: 'testing-bf7e5',
    storageBucket: 'testing-bf7e5.appspot.com',
    androidClientId: '163795736504-7bgshls305t5r6f8d80qmeuus4gqdu72.apps.googleusercontent.com',
    iosClientId: '163795736504-5l74epgjou0ss2it6h1rjlfbbm1gq7dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorwhisper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCk9GfxK8xXIrRWG-zjsuODBI4xrAdX1E',
    appId: '1:163795736504:ios:137df7707817c591e0614d',
    messagingSenderId: '163795736504',
    projectId: 'testing-bf7e5',
    storageBucket: 'testing-bf7e5.appspot.com',
    androidClientId: '163795736504-7bgshls305t5r6f8d80qmeuus4gqdu72.apps.googleusercontent.com',
    iosClientId: '163795736504-5l74epgjou0ss2it6h1rjlfbbm1gq7dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.majorwhisper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBiYw_-AWeeFVOifODL0SGxXf27H2bY8',
    appId: '1:163795736504:web:4778ac2a2c93de78e0614d',
    messagingSenderId: '163795736504',
    projectId: 'testing-bf7e5',
    authDomain: 'testing-bf7e5.firebaseapp.com',
    storageBucket: 'testing-bf7e5.appspot.com',
    measurementId: 'G-7HT9EDJ3JM',
  );

}